# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version:
          - 0.10.x
          - 0.12.x
          - 4.x
          - 6.x
          - 8.x
          # - 10.x
          # - 12.x
          # - 14.x
          # - 16.x
          # - 18.x
          # - 20.x

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # TODO: Enable cache when checking in package lockfile to git
        # cache: 'npm'
    - run: npm install
    - run: npm run test
